!function(t){var e={};function n(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return t[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=t,n.c=e,n.d=function(t,e,r){n.o(t,e)||Object.defineProperty(t,e,{configurable:!1,enumerable:!0,get:r})},n.r=function(t){Object.defineProperty(t,"__esModule",{value:!0})},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=2)}([function(t,e){!function(){t.exports=this.wp.element}()},function(t,e,n){var r;
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
/*!
  Copyright (c) 2017 Jed Watson.
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/
!function(){"use strict";var n={}.hasOwnProperty;function o(){for(var t=[],e=0;e<arguments.length;e++){var r=arguments[e];if(r){var c=typeof r;if("string"===c||"number"===c)t.push(r);else if(Array.isArray(r)&&r.length){var a=o.apply(null,r);a&&t.push(a)}else if("object"===c)for(var i in r)n.call(r,i)&&r[i]&&t.push(i)}}return t.join(" ")}void 0!==t&&t.exports?(o.default=o,t.exports=o):void 0===(r=function(){return o}.apply(e,[]))||(t.exports=r)}()},function(t,e,n){"use strict";n.r(e);var r=n(0),o=n(1),c=n.n(o),a=wp.blocks.registerBlockType,i=wp.editor,l=i.BlockControls,s=i.PlainText,u=(i.InspectorControls,i.PanelColorSettings,i.ContrastChecker,i.getColorClassName,wp.element),p=u.RawHTML,b=u.Fragment,m=wp.components,f=m.Disabled,v=m.SandBox,d=wp.compose.withState,w=wp.i18n.__,y=c()("wp-block-button","ystdb-btn-wrap","wp-block-html"),h={width:"100%"};a("ystdb/afi-btn",{title:"アフィリエイトリンクボタンブロック",description:"アフィリエイトリンクなど、入力したリンクをボタン形式で表示します。",icon:"embed-generic",keywords:[w("link"),w("button"),"button"],category:"ystdb",attributes:{content:{type:"string"}},supports:{className:!1},edit:d({isPreview:!1})(function(t){var e=t.attributes,n=t.setAttributes,o=t.setState,c=t.isPreview;return Object(r.createElement)("div",{className:y,style:h},Object(r.createElement)(b,null,Object(r.createElement)(l,null,Object(r.createElement)("div",{className:"components-toolbar"},Object(r.createElement)("button",{className:"components-tab-button ".concat(c?"":"is-active"),onClick:function(){o({isPreview:!1})}},Object(r.createElement)("span",null,"HTML")),Object(r.createElement)("button",{className:"components-tab-button ".concat(c?"is-active":""),onClick:function(){o({isPreview:!0})}},Object(r.createElement)("span",null,w("Preview"))))),Object(r.createElement)(f.Consumer,null,function(){return c?Object(r.createElement)(v,{html:e.content,style:"\n    html,body,:root {\n        margin: 0 !important;\n        padding: 0 !important;\n        overflow: visible !important;\n        min-height: auto !important;\n    }\n"}):Object(r.createElement)(s,{value:e.content,onChange:function(t){return n({content:t})},placeholder:"アフィリエイトタグを入力","aria-label":w("HTML")})})))}),save:function(t){var e=t.attributes;return Object(r.createElement)("div",{className:y},Object(r.createElement)(p,null,e.content))}})}]);