name: Develop Build
on:
  push:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'develop'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug

      - name: Check PHP Version
        run: php -v

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: lint
        run: npm run lint

      - name: Failed Test
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "Failure : lint"
          color: 0x962305
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: failure()

  codeCheck:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4', '8.1', '8.2', '8.3', '8.4' ]
    name: PHP Error Check (PHP ${{ matrix.php }})
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'develop'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug

      - name: php -l
        run: bash bin/php-l.sh

      - name: Failed Test
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "Failure : Error Check"
          color: 0x962305
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: failure()

  test:
    name: UnitTest
    needs: [ lint, codeCheck ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'develop'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Failed Test
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "Failure : Test"
          color: 0x962305
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: failure()

  release:
    name: Release
    needs: [ lint, codeCheck, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'develop'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip
        run: npm run zip

      - name: Release File Copy
        run: npm run copy:develop

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./upload/
          server-dir: ${{ secrets.FTP_REMOTE_DIR_DEVELOP }}/

      - name: Notify Deployment Develop Version for Discord
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "[yStandard Blocks]開発バージョンのアップデート準備OK！"
          color: 0x059669
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
