name: Production Build
on:
    push:
        branches:
            - production
jobs:
    FTP-Deploy-Action:
        name: FTP-Deploy-Action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: 'production'

            - name: npm install
              run: npm install

            - name: Build
              run: npm run build

            - name: Zip
              run: npm run zip

            - name: Release File Copy
              run: npm run copy:production

            - name: FTP-Deploy-Action
              uses: SamKirkland/FTP-Deploy-Action@2.0.0
              env:
                  FTP_SERVER: ${{ secrets.FTP_SERVER }}
                  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  LOCAL_DIR: upload
                  REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR_PRODUCTION }}
                  ARGS: --verbose

            - name: Notify Deployment Develop Version for Discord
              uses: sarisia/actions-status-discord@v1
              with:
                  nodetail: true
                  title: '[yStandard Blocks]新バージョンのアップデート準備OK！'
                  color: 0x059669
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              if: success()
