name: Production Build
on:
  push:
    branches:
      - production
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - name: npm ci
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Zip
        run: npm run zip

      - name: Release File Copy
        run: npm run copy:production

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./upload/
          server-dir: ${{ secrets.FTP_REMOTE_DIR_PRODUCTION }}/
          log-level: verbose

  notify:
    name: Notify
    needs: [ deploy ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: "Failure : Production Build"
          color: 0x962305
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify success
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: '[yStandard Blocks]新バージョンのアップデート準備OK！'
          color: 0x059669
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
