name: Production Build
on:
  push:
    branches:
      - production
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 'production'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip
        run: npm run zip

      - name: Release File Copy
        run: npm run copy:production

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./upload/
          server-dir: ${{ secrets.FTP_REMOTE_DIR_PRODUCTION }}/
          log-level: verbose

      - name: Notify Deployment Production Version for Discord
        uses: sarisia/actions-status-discord@v1
        with:
          nodetail: true
          title: '[yStandard Blocks]新バージョンのアップデート準備OK！'
          color: 0x059669
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
