name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  convert:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
